{% set version = "13.3.rel1" %}

package:
  name: gcc-arm-none-eabi
  # conda package versions do not permit hyphens, replace with '.'
  version: {{ version|replace('-', '.') }}

source:
  url: https://developer.arm.com/-/media/Files/downloads/gnu/{{ version }}/binrel/arm-gnu-toolchain-{{ version }}-darwin-arm64-arm-none-eabi.tar.xz # [osx and arm64]
  sha256: fb6921db95d345dc7e5e487dd43b745e3a5b4d5c0c7ca4f707347148760317b4 # [osx and arm64]
  url: https://developer.arm.com/-/media/Files/downloads/gnu/{{ version }}/binrel/arm-gnu-toolchain-{{ version }}-darwin-x86_64-arm-none-eabi.tar.xz # [osx and x86_64]
  sha256: 1ab00742d1ed0926e6f227df39d767f8efab46f5250505c29cb81f548222d794 # [osx and x86_64]

  url: https://developer.arm.com/-/media/Files/downloads/gnu/{{ version }}/binrel/arm-gnu-toolchain-{{ version }}-x86_64-arm-none-eabi.tar.xz # [linux and x86_64]
  sha256: 95c011cee430e64dd6087c75c800f04b9c49832cc1000127a92a97f9c8d83af4 # [linux and x86_64]
  url: https://developer.arm.com/-/media/Files/downloads/gnu/{{ version }}/binrel/arm-gnu-toolchain-{{ version }}-aarch64-arm-none-eabi.tar.xz # [linux and aarch64]
  sha256: c8824bffd057afce2259f7618254e840715f33523a3d4e4294f471208f976764 # [linux and aarch64]

  url: https://developer.arm.com/-/media/Files/downloads/gnu/{{ version }}/binrel/arm-gnu-toolchain-{{ version }}-mingw-w64-i686-arm-none-eabi.zip # [win and x86_64]
  sha256: e46fda043c0ce83582bc8db4b3ef85f77f4beb7333344c2f4193c17e1167a095 # [win and x86_64]

build:
  string: '0'

test:
  commands:
    - arm-none-eabi-gcc --version

about:
  home: https://developer.arm.com/Tools%20and%20Software/GNU%20Toolchain
  license: GPL
  summary: Arm GNU Toolchain
