on:
  workflow_dispatch:
    inputs:
      PACKAGE_DIR:
        description: "set package dir to build and archive your package"
        required: true

jobs:
  build:
    name: 🛠️ build on ${{ matrix.platform }}

    strategy:
      # run all targets to completion, even if one fails
      fail-fast: false
      matrix:
        platform: [macos-15, macos-15-intel, ubuntu-24.04, ubuntu-24.04-arm, windows-2025]
    runs-on: ${{ matrix.platform }}

    # set bash to be a login shell, so that /etc/profile is sourced and conda
    # works
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v6

      - name: Conda environment creation and activation
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: 3.11
          environment-file: environment.yml
          auto-update-conda: false
          auto-activate-base: false
          show-channel-urls: true

      - name: Build and upload the conda packages
        uses: uibcdf/action-build-and-upload-conda-packages@v1.5.0
        with:
          meta_yaml_dir: ${{ github.event.inputs.PACKAGE_DIR }}
          user: EliaCereda
          token: ${{ secrets.ANACONDA_TOKEN }} # Replace with the name of your Anaconda Token secret
